# Generated by Django 4.0.4 on 2022-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=144)),
                ('message_email', models.CharField(max_length=144)),
                ('message', models.TextField()),
                ('dateANDtiME', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
