# Generated by Django 4.0.4 on 2022-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_name',
            field=models.TextField(),
        ),
    ]
