# Generated by Django 4.0.4 on 2022-05-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contact_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_email',
        ),
    ]
