# Generated by Django 4.0.4 on 2022-05-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_contact_message_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Messages',
        ),
    ]
