# Generated by Django 4.0.4 on 2022-05-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_contact_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Contact',
        ),
    ]
