# Generated by Django 4.0.4 on 2022-05-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
