# Generated by Django 4.0.3 on 2022-05-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_bookapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookapp',
        ),
    ]
