# Generated by Django 4.0.4 on 2022-05-07 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_contact_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_name',
            field=models.TextField(),
        ),
    ]
