# Generated by Django 4.0.4 on 2022-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_contact_message_email_alter_contact_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bookapp',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
